name: Langulus::Anyness CI
on: [push, pull_request] # Trigger on pushes to all branches and for all pull-requests

jobs:
  build:
    strategy:
      fail-fast: false # do not abort on a failed job
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build: [Debug, RelWithDebInfo]
        safety: ['-DLANGULUS_ENABLE_SAFE_MODE=ON']
        architecture: [x86, x64]
        managed: ['-DLANGULUS_FEATURE_MANAGED_MEMORY=OFF', '-DLANGULUS_FEATURE_MANAGED_MEMORY=ON']
        include:
          - os: ubuntu-22.04
            cxx: [g++, clang++]
          - os: windows-latest
            cxx: [cl]
          - os: ubuntu-22.04
            architecture: x86
            cmake_args: "-DCMAKE_CXX_FLAGS=-m32"
          - os: ubuntu-22.04
            architecture: x64
            cmake_args: "-DCMAKE_CXX_FLAGS=-m64"
          - os: windows-latest
            architecture: x86
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32"
          - os: windows-latest
            architecture: x64
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64"
          - managed: '-DLANGULUS_FEATURE_MANAGED_MEMORY=OFF'
            suffix: ''
          - managed: '-DLANGULUS_FEATURE_MANAGED_MEMORY=ON'
            suffix: '-managed'

    name: "${{matrix.os}}-${{matrix.cxx}}-${{matrix.build_type}}-${{matrix.architecture}}${{matrix.suffix}}"
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_CXX_COMPILER=${{matrix.cxx}} -S . -B out/${{name}} -DCMAKE_BUILD_TYPE=${{matrix.build}} ${{matrix.cmake_args}} ${{matrix.managed}} ${{matrix.safety}}
      - name: Build
        run: cmake --build out/${{name}} --config ${{matrix.build}}
      - name: Test
        run: cd out/${{name}} && ctest -V -C ${{matrix.build}}